name: Build and Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (test or prod)'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - prod

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for setuptools_scm to determine version from git

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        # Install dependencies explicitly to ensure they're available for tests
        pip install todoist-api-python python-dotenv pytest pytest-asyncio mcp-server pydantic aiohttp

    # - name: Run pre-commit checks
    #   run: |
    #     pre-commit run --all-files

    - name: Test with pytest
      run: |
        pytest
      env:
        TODOIST_API_TOKEN: "mock_token_for_testing"

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write  # For creating GitHub releases
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for setuptools_scm to determine version from git

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build
        # Display the built package names for debugging
        echo "Built packages:"
        ls -la dist/

    # Add a verification step to check version format
    - name: Verify version format
      run: |
        if ls dist/*.whl | grep -q '+'; then
          echo "WARNING: Package version contains '+' which is not allowed by PyPI"
          echo "This is likely a development version. For proper releases, use git tags."
          # Only fail for tag-triggered workflows
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            echo "ERROR: Tagged releases should not contain '+' in version"
            exit 1
          fi
        else
          echo "Version format is valid for PyPI"
        fi

    - name: Generate changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        configuration: ".github/changelog-config.json"
        ignorePreReleases: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        body: |
          # Changelog
          ${{ steps.github_release.outputs.changelog }}
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to Test PyPI
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.release_type == 'test'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
        verify-metadata: true
        verbose: true

    - name: Publish to PyPI
      if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.release_type == 'prod')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        verify-metadata: true
        verbose: true
